{% set name = "ezgooey" %}
{% set version = "2.7.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/twardoch/ezgooey/archive/v{{ version }}.tar.gz
  sha256: eb4b1bba00ba6910fa17d59a5802253d8e14159cc7784854a554f71c790269eb

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - colored >=1.4.2
    - gooey >=1.0.8
    - python >={{ python_min }}

test:
  imports:
    - ezgooey
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://twardoch.github.io/ezgooey/
  license: MIT
  license_file: LICENSE
  summary: Simplifies making GUI+CLI apps with Gooey
  dev_url: https://github.com/twardoch/ezgooey/
  description: |
    `Gooey` is a Python package, which lets you turn argparse-based CLI apps into cross-platform GUI apps. `ezgooey.ez` makes this even simpler.

extra:
  recipe-maintainers:
    - HeavyTony2
